### ISSUE TITLE
Error loading module in Nginx

### ISSUE THREAD

**Issue by FullStackIndie** [open-telemetry/opentelemetry-cpp-contrib#106]
**Describe your environment**
I am running Ubuntu 20.04 LTS Stable and I downloaded the latest stable release of OpenTelemetry nginx module from the Github Actions artificats section.
[](https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx)

I am using "nginx:latest" in docker container. I am running "otel/opentelemetry-collector:latest" as well in docker container and both are started  with Docker compose. All config files here [https://gist.github.com/FullStackIndie/d3fd2234e34348226b696758ba7bdbba](url)

**Steps to reproduce**
I use my docker compose up -d and my webserver(Nginx) crashes almost instantly with the error below.

**What is the expected behavior?**
I expect Nginx to load the open telemtry module for nginx properly so I can start tracing requests.

**What is the actual behavior?**
I keep getting an error everytime I nginx tries to laod the Module for open telemetry.

2022/02/22 06:03:46 [emerg] 1#1: dlopen() "/etc/nginx/modules/otel_ngx_module.so" failed (/etc/nginx/modules/otel_ngx_module.so: undefined symbol: pcre_exec) in /etc/nginx/nginx.conf:1

nginx: [emerg] dlopen() "/etc/nginx/modules/otel_ngx_module.so" failed (/etc/nginx/modules/otel_ngx_module.so: undefined symbol: pcre_exec) in /etc/nginx/nginx.conf:1**

Any help is greatly appreciated, thanks!!!

**Comment by nicolastakashi** [comment]
Same issue here!

**Comment by tobiasstadler** [comment]
I think the problem is, that the module is built with PCRE support, while the nginx in the image isn't.

**Comment by FullStackIndie** [comment]
Looks like my Docker container running Nginx doesn't come with the **with-pcre-jit** configuration parameter. When running Nginx on host server, instead of Docker container, it does come with PCRE support built in so I will try that later. thanks for the help!!! @tobiasstadler
