### ISSUE TITLE
How to report traces directly to jaeger.

### ISSUE THREAD

**Issue by nicolastakashi** [open-telemetry/opentelemetry-cpp-contrib#107]
Since the Otel implementation allows us to send spans directly to backend instances, how can we send spans directly to jaeger without setting up an OTel Collector?

**Comment by lalitb** [comment]
otel-cpp provides Jaeger exporter to send spans directly from application to backend. More information here:

https://github.com/open-telemetry/opentelemetry-cpp/tree/main/exporters/jaeger

**Comment by mc-chaos** [comment]
@nicolastakashi : Gould this closed?
Regards, Sascha

**Comment by nicolastakashi** [comment]
Hey @mc-chaos sure, thanks for your supporting!
