### ISSUE TITLE
Publish .so artifacts from the otel-webserver-module

### ISSUE THREAD

**Issue by phillipuniverse** [open-telemetry/opentelemetry-cpp-contrib#192]
**Is your feature request related to a problem?**
No, usability only.

**Describe the solution you'd like**

It would be really nice if the `otel-webserver-module` published the final built `.so` artifacts somewhere. The current nginx and httpd instrumentation publish them as action artifacts, [example](https://github.com/open-telemetry/opentelemetry-cpp-contrib/actions/runs/2533678779):

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/684275/179988251-3c84206f-6aa7-4054-aca7-698cdf08b590.png">

**Describe alternatives you've considered**

The other option is to go through the build instructions in the README to build the image, then grab the `.so` files from `/opt/opentelemetry-webserver-sdk/sdk_lib/lib` and `/opt/opentelemetry-webserver-sdk/WebServerModule/Nginx/ngx_http_opentelemetry_module.so`.

**Comment by DebajitDas** [comment]
@phillipuniverse 
This has been already taken care and artifacts are published on every github actions on 'otel-webserver-module'. Please find the same here https://github.com/open-telemetry/opentelemetry-cpp-contrib/actions/runs/2711112662

**Comment by DebajitDas** [comment]
@phillipuniverse we are updating the README with more details https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/196

Thanks for your suggestion.

**Comment by phillipuniverse** [comment]
@DebajitDas awesome! README updates look great!!

**Comment by DebajitDas** [comment]
@phillipuniverse We have made a release tag for webserver and the same can be downloaded from https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/tag/webserver%2Fv1.0.0

**Comment by DebajitDas** [comment]
Closing this issue as the requirement has been addressed.

**Comment by phillipuniverse** [comment]
Really awesome stuff @DebajitDas thank you! I can’t wait to really try this out and give further feedback!!
