### ISSUE TITLE
Status of otel_ngx_module vs otel-webserver-module is unclear

### ISSUE THREAD

**Issue by kamalmarhubi** [open-telemetry/opentelemetry-cpp-contrib#208]
The status of these two different ways to get opentelemetry into nginx is pretty unclear. They have entirely separate authors, and are both have recent-ish updates.

@seemk @tobiasstadler @DebajitDas @kpratyus as the primary contributors to the two modules: could you help clear this up a bit? Will they coexist?

**Comment by lalitb** [comment]
@kamalmarhubi  - Both will co-exists as long as they are maintained. Would suggest you use one which suits your requirements.

**Comment by lalitb** [comment]
Closing this issue, please reopen if you still have any questions.

**Comment by gregory112** [comment]
@lalitb @kamalmarhubi I too am curious about this, both seems to do the same thing, but with completely different configuration syntaxes and build steps. Previously I thought both do different things and tried to build and load both, but then my Nginx stops responding to any requests until timeout.

Perhaps it is better to provide documentations in both of them as why both differ. I personally prefer otel_ngx_module as it follows many Nginx conventions while otel-webserver-module uses Apache httpd naming conventions. I think it is better for otel-webserver-module to drop support for Nginx completely.
