### ISSUE TITLE
License Header in OTEL Webserver Modules shows all "Appdynamics" License 

### ISSUE THREAD

**Issue by SaschaBrechmannVHV** [open-telemetry/opentelemetry-cpp-contrib#215]
**Describe your environment** 
The Header of the OTEL Webserver Module files shows all "Appdynamics License".
See Screenshot at the end 

**What is the expected behavior?**
Should we Change Appdynamics to Opentelemetry or some thing?

**What is the actual behavior?**
Do not see content from the commercial "upstream" project

**Additional context**
![image](https://user-images.githubusercontent.com/77098451/192576648-cbaf633e-a764-48d3-80e4-eca708aa2670.png)

**Comment by DebajitDas** [comment]
Hi @kpratyus, please check this with Cisco stakeholders.

**Comment by DebajitDas** [comment]
Updated the License Information. PR is https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/233
Hence closing the ticket
