### ISSUE TITLE
Update to release 1.0.3 bug occurs

### ISSUE THREAD

**Issue by sonjinho** [open-telemetry/opentelemetry-cpp-contrib#247]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

release 1.0.3
ubuntu 20.04 (not k8s)
nginx 1.23.1

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

update to 1.0.3

libprotobuf error occurs

> [libprotobuf ERROR /grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'opentelemetry.proto.common.v1.AnyValue.string_value' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes

full log
> 2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: Interaction begin successful, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: otel_stopInteraction: Stopping the Interaction for: ngx_http_index_module while sending response to client, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: stopMonitoringRequest: Stopping the Request Monitoring while logging request, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
2022/12/15 15:55:00 [error] 273268#273268: *1 mod_opentelemetry: stopMonitoringRequest: Request Ends with result code: 0 while logging request, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost"
[libprotobuf ERROR /grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'opentelemetry.proto.common.v1.AnyValue.string_value' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.

**What is the expected behavior?**
What did you expect to see?
Sending opentelemetry span to opentelemetry collector

**What is the actual behavior?**
What did you see instead?
Cannot Sending opentelemetry collector, and also occur error on opentelemetry collector
`2022-12-15T15:55:05.927+0900	error	exporterhelper/queued_retry.go:183	Exporting failed. The error is not retryable. Dropping data.	{"kind": "exporter", "name": "otlp", "error": "Permanent error: rpc error: code = Unknown desc = ", "dropped_items": 14}
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
	go.opentelemetry.io/collector@v0.44.0/exporter/exporterhelper/queued_retry.go:183
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
	go.opentelemetry.io/collector@v0.44.0/exporter/exporterhelper/traces.go:136
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
	go.opentelemetry.io/collector@v0.44.0/exporter/exporterhelper/queued_retry_inmemory.go:105
go.opentelemetry.io/collector/exporter/exporterhelper/internal.consumerFunc.consume
	go.opentelemetry.io/collector@v0.44.0/exporter/exporterhelper/internal/bounded_memory_queue.go:99
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue).StartConsumers.func2
	go.opentelemetry.io/collector@v0.44.0/exporter/exporterhelper/internal/bounded_memory_queue.go:78
`

**Additional context**

Using version 1.0.2 working sending fine, but has same bug [235](https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/235)

**Comment by EricSoroos** [comment]
I'm seeing this on a simple isolated test image, for all requests:
```
from nginx:1.23.1
run apt-get update && apt-get install -y unzip
ADD https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/download/webserver%2Fv1.0.3/opentelemetry-webserver-sdk-x64-linux.tgz /opt
RUN cd /opt ; unzip opentelemetry-webserver-sdk-x64-linux.tgz.zip; tar xvfz opentelemetry-webserver-sdk-x64-linux.tgz
RUN cd /opt/opentelemetry-webserver-sdk; ./install.sh
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/opentelemetry-webserver-sdk/sdk_lib/lib
add ./nginx.conf /etc/nginx/nginx.conf
```
(essentially following https://opentelemetry.io/blog/2022/instrument-nginx/)

Then

```
...
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_stopInteraction: Stopping the Interaction for: ngx_http_random_index_module, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: Starting a new module interaction for: ngx_http_index_module, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_payload_decorator: Key : tracestate, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_payload_decorator: Value : , client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_payload_decorator: Key : traceparent, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_payload_decorator: Value : 00-80cce9e5e8fc8371bbecf12d7ecf745d-517ac555ef0b6de3-01, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: Interaction begin successful, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_startInteraction: It is not a main Request, not starting interaction, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: otel_stopInteraction: Stopping the Interaction for: ngx_http_index_module while sending response to client, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: stopMonitoringRequest: Stopping the Request Monitoring while logging request, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 2022/12/22 17:47:42 [error] 34#34: *4 mod_opentelemetry: stopMonitoringRequest: Request Ends with result code: 0 while logging request, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
nginx_1      | 172.22.0.1 - - [22/Dec/2022:17:47:42 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.68.0" "-"
nginx_1      | 2022/12/22 17:47:42 [info] 34#34: *4 client 172.22.0.1 closed keepalive connection
nginx_1      | [libprotobuf ERROR /grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'opentelemetry.proto.common.v1.AnyValue.string_value' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
nginx_1      | [libprotobuf ERROR /grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:577] String field 'opentelemetry.proto.common.v1.AnyValue.string_value' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
```

**Comment by kpratyus** [comment]
https://github.com/open-telemetry/opentelemetry-cpp-contrib/actions/runs/3742143838

@sonjinho could you please try using the artefact from here?

**Comment by sonjinho** [comment]
@kpratyus Thank you so much! It is working fine!

**Comment by EricSoroos** [comment]
LGTM

**Comment by DebajitDas** [comment]
Closing as fixed [PR](https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/249)
