### ISSUE TITLE
Nginx opentelemetry module not working in  Nginx 1.18 or 1.22

### ISSUE THREAD

**Issue by uttammajigithub** [open-telemetry/opentelemetry-cpp-contrib#306]
Hi team,

I have tested nginx 1.18.0 with http module 1.0.0 and 1.0.1, but got the error that ngx_http_opentelemetry_module.so is not binary compatible.

Also tested nginx 1.22.1 with http module 1.0.2 and 1.0.3 but got the error that ngx_http_opentelemetry_module.so file is for 1.22.0 version and it will not work for 1.22.1 version. Here we are using higher version of nginx,
but it is not supporting ngx_http_opentelemetry_module.so which was created in lower version.

Could you please check the issue and suggest quick resolution.

Thanks
Uttam

**Comment by FullStackIndie** [comment]
Are you using the deprecated version for Nginx 1.18 located in the [nginx folder](https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx) or the new version for Nginx stable version (1.22.0) and mainline versions(1.23.0, 1.23.1). in the [otel-webserver-module ](https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/otel-webserver-module) ???

**Comment by senthilmnathan** [comment]
> Are you using the deprecated version for Nginx 1.18 located in the [nginx folder](https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx) or the new version for Nginx stable version (1.22.0) and mainline versions(1.23.0, 1.23.1). in the [otel-webserver-module ](https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/otel-webserver-module) ???

I am running into the same issue. I am using opentelemetry-webserver-sdk version 1.0.0 and Redhat nginx 1.18.0. I get the error. I am using RedHat EL version 8.7

`nginx: [emerg] module "/usr/lib64/nginx/modules/ngx_http_opentelemetry_module.so" is not binary compatible in /usr/share/nginx/modules/ngx_http_opentelemetry_module.so" is not binary compatible in /usr/share/nginx/modules/mod-http-opentelemetry.conf`

1. Does this Opentelemetry WebServer library support RedHat OS and RedHat Nginx binary ?
2. If I need to run telemetry on Redhat nginx latest version (1.22.1) how do I go about building the library ? Please advice

Thanks
Senthil Nathan M

**Comment by johnbayo** [comment]
I am using registry.access.redhat.com/ubi8/nginx-122. i also have issues. i tested with 1.18 and also got the same erroras above. it doesnt seem to work with any redhat images

```
 2023/09/15 10:42:19 [emerg] 14#0: module "/opt/app-root/src/opentelemetry-webserver-sdk/WebServerModule/Nginx/1.22.0/ngx_http_opentelemetry_module.so" version 1022000 instead of 1022001 in /etc/nginx/nginx.conf:1
nginx: [emerg] module "/opt/app-root/src/opentelemetry-webserver-sdk/WebServerModule/Nginx/1.22.0/ngx_http_opentelemetry_module.so" version 1022000 instead of 1022001 in /etc/nginx/nginx.conf:1
```
