### ISSUE TITLE
Target "otel_ngx_module" links to target "CURL::libcurl" but the target was   not found.

### ISSUE THREAD

**Issue by tippexs** [open-telemetry/opentelemetry-cpp-contrib#33]
Hi, 

I am working on a universal docker-build container image to build the NGINX OTEL module. 

My baseimage is `ubunut:20.04`.  After building grpc, cmake, googletest with benchmark and opentelemetry I was able to start building the NGINX Module.

While running `cmake` I received the following error:

```
root@825df8ee05d0:/opentelemetry-cpp-contrib/instrumentation/nginx/build# cmake ..
-- nginx: using version 1.19.9
-- nginx: --with-compat enabled
-- Configuring done
CMake Error at CMakeLists.txt:12 (add_library):
  Target "otel_ngx_module" links to target "CURL::libcurl" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
I have modified the `CMakeLists.txt`
and have added 

```
find_package( CURL REQUIRED )
```
With this small fix its working just fine. Is this a docker issue? Have you seen this issue before?

**Steps to reproduce**
`git clone` inside the docker container and issue
`cmake ..`

**What is the expected behavior?**
No errors just my lovely NGINX Module file 💚

**What is the actual behavior?**
Error message shown above

**Comment by noliva** [comment]
Hello @tippexs, do you plan on contributing back that docker-build container? I was literally doing the same thing now to build the module

**Comment by tippexs** [comment]
Sure thing @noliva Gimme a couple of more hours today and let me share the Dockerfile. All tests on my end are looking good so far.

**Comment by seemk** [comment]
Looks like curl has crept in from somewhere, I'll take a look

**Comment by seemk** [comment]
Can you post the build options for opentelemetry-cpp?

For example CI build opentelemetry-cpp with the following settings and the error doesn't appear there:

```
git clone --shallow-submodules --depth 1 --recurse-submodules -b v0.7.0 \
  https://github.com/open-telemetry/opentelemetry-cpp.git \
  && cd opentelemetry-cpp \
  && mkdir build \
  && cd build \
  && cmake -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/install \
    -DCMAKE_PREFIX_PATH=/install \
    -DWITH_OTLP=ON \
    -DBUILD_TESTING=OFF \
    -DWITH_EXAMPLES=OFF \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    .. \
  && make -j2 \
  && make install
```

So I'm wondering whether it could be that if zipkin exporter causes it
