### ISSUE TITLE
Release v1.0.4 has the wrong format or file ending

### ISSUE THREAD

**Issue by Paso** [open-telemetry/opentelemetry-cpp-contrib#341]
The newest release binary v1.0.4 is called .tgz like the previous ones but the file format is not tar+gz. I could extract it by first using "unzip" and then "tar -xz" so it's probably a tar+gz+zip which doesn't make much sense.

**Comment by mmmvvvppp** [comment]
I'd agree with your assessment of the zip around a tar+gz. `unzip -Z` identifies as a zip:
```
unzip -Z opentelemetry-webserver-sdk-x64-linux.tgz 
Archive:  opentelemetry-webserver-sdk-x64-linux.tgz
Zip file size: 14423713 bytes, number of entries: 1
?rw-r--r--  2.0 unx 14560293 bl defN 23-Nov-20 06:50 opentelemetry-webserver-sdk-x64-linux.tgz
1 file, 14560293 bytes uncompressed, 14423517 bytes compressed:  0.9%
```

`unzip -p opentelemetry-webserver-sdk-x64-linux.tgz | tar -zx` does work for me.  Thank you.

**Comment by DebajitDas** [comment]
Updated the file. It should be tar + gz as expected.
