### ISSUE TITLE
Add support for b3multi

### ISSUE THREAD

**Issue by zdmytriv** [open-telemetry/opentelemetry-cpp-contrib#36]
**Is your feature request related to a problem?**
Need support for b3-multi for nginx module. https://github.com/openzipkin/b3-propagation#multiple-headers

**Describe the solution you'd like**
Implement b3-multi in similar fashion like it is with simple b3 just do not concat trace-span-sampled into on header.

Right now header looks like
```
"B3": "2605e09e4efca19056beee12767f6287-426bf077362e8477-1",
```
for b3-multi there should be 3 headers
```
X-B3-TraceId: 2605e09e4efca19056beee12767f6287
X-B3-SpanId: 426bf077362e8477
X-B3-Sampled: 1
```

**Comment by kuzaxak** [comment]
@ThomsonTan Could you please have a look?

**Comment by seemk** [comment]
Fixed with https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/495
