### ISSUE TITLE
Can't use find_package to locate opentelemetry_fluentd

### ISSUE THREAD

**Issue by zurex** [open-telemetry/opentelemetry-cpp-contrib#477]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.

environment: Linux based system.
platform: x86-64
build system: CMake-3.27 & LLVM-18

**Steps to reproduce**
Describe exactly how to reproduce the error. Include a code sample if applicable.

```CMake
find_package(opentelemetry-fluentd CONFIG)
cmake_print_variables(OPENTELEMETRY_CPP_FLUENTD_LIBRARIES)
```

**What is the expected behavior?**
What did you expect to see?
`opentelemetry-cpp-fluentd::trace;opentelemetry-cpp-fluentd::logs`

**What is the actual behavior?**
What did you see instead?

Empty

**Additional context**

In the description part of `exporters/fluentd/cmake/opentelemetry-cpp-fluentd-config.cmake.in`, it should return :
* opentelemetry-cpp-fluentd::trace
* opentelemetry-cpp-fluentd::logs

But it try to test the tar exiting or not by ` if(TARGET opentelemetry-fluentd-cpp::${_TEST_TARGET})`, in this package it does't provide such  project named as `opentelemetry-fluentd-cpp`. It should be `opentelemetry-fluentd`.

**Comment by marcalff** [comment]
Closing, fixed by #478
