### ISSUE TITLE
How to quickly deploy opentelemetry-cpp-contrib-nginx?

### ISSUE THREAD

**Issue by wajika** [open-telemetry/opentelemetry-cpp-contrib#63]
Hello everyone, I want to test the nginx opentracing+elastic apm solution, when I am building
I found it very troublesome when opentelemetry-cpp-contrib-nginx. Opentelemetry-cpp-contrib requires grpc, and grpc requires gcc 5.4+... The system I use is centos 7.7, and there are a lot of troubles in compiling grpc, in short, it’s a bit bad .

I am thinking that if the community can openly provide the otel_ngx_module.so file, I will directly compile it into nginx, which is much easier. Because I just want to test the effect of nginx + elastic apm.

By the way, I want to test the binary version of nginx.
If I am wrong, please correct me

**Comment by zhuizhuhaomeng** [comment]
got the same problem

**Comment by seemk** [comment]
I agree the amount of dependencies is annoying (e.g. grpc). What's the gcc version available on CentOS 7.7?

**Comment by iquirino** [comment]
#81 Running with alpine linux on docker.

**Comment by wajika** [comment]
@iquirino @gbschenkel thanks
