### ISSUE TITLE
Instruments here can't be search in https://opentelemetry.io/registry/

### ISSUE THREAD

**Issue by katepangLiu** [open-telemetry/opentelemetry-cpp-contrib#66]
No result:
https://opentelemetry.io/registry/?s=nginx&component=&language=
https://opentelemetry.io/registry/?s=http&component=&language=

**Comment by lalitb** [comment]
thanks for noticing this. Will add this to the registry.

**Comment by lalitb** [comment]
This should work now : https://github.com/open-telemetry/opentelemetry.io/pull/892
