### ISSUE TITLE
nginx: `opentelemetry_propagate` in `http` block not honored

### ISSUE THREAD

**Issue by spencerwilson** [open-telemetry/opentelemetry-cpp-contrib#67]
**Describe your environment**

```
$ nginx -V
nginx version: nginx/1.20.0
built by gcc 7.3.1 20180712 (Red Hat 7.3.1-13) (GCC)
built with OpenSSL 1.1.1g FIPS  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-compat --with-debug --with-file-aio --with-google_perftools_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'

$ uname -rs
Linux 4.14.248-189.473.amzn2.x86_64
```

EC2 AMI ID ami-060f1292334857878, name aws-elasticbeanstalk-amzn-2.0.20211001.64bit-eb_nodejs12_amazon_linux_2-hvm-2021-10-16T18-34

Using nginx instrumentation in https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/30e872e1d91cb696b48418300fddd8f9fc36b914/instrumentation/nginx, built after manually building grpc, then opentelemetry-cpp.

**Steps to reproduce**
See this gist for output of `nginx -T` and TOML config: https://gist.github.com/spencerwilson/3652d37a494710451afef9ee472ae7c3

**What is the expected behavior?**
Requests nginx makes to http://127.0.0.1:4000 include `traceparent` header (at least) in every request.

**What is the actual behavior?**
Application listening on port 4000 isn't getting any requests with any W3C Trace Context headers.

**Additional context**

- The only lines in /var/log/nginx/error.log around `nginx -s reload` are like `2021/11/13 07:17:03 [notice] 12367#12367: signal process started`; nothing about OpenTelemetry
- In addition to `nginx -s reload` I also tried quitting and starting it again
- Nothing in /var/log/nginx/access.log other than normal access logs
- User `root` is the owner of the nginx master process, user `nginx` is owner of the worker processes. Both users can read both /etc/nginx/conf.d/opentelemetry.conf and /etc/nginx/conf.d/opentelemetry_config.toml
- I'm not actually running any process on localhost:4317 (where the OTLP/gRPC exporter is configured in the TOML to connect to), in case that could cause a problem.

My expectation is that the `include` on L24 in the nginx config gist file would be putting my
```
opentelemetry_config /etc/nginx/conf.d/opentelemetry_config.toml;
opentelemetry_propagate;
```
directives into the `http` block—which the module's README says is a supported place to put them.

My C++ and Nginx skills are poor so I appreciate any suggestions of other things to check. Thank you!

**Comment by tobiasstadler** [comment]
I think this is a bug.

Can you please try to place `opentelemetry_propagate;` in the location block of `proxy_pass          http://127.0.0.1:4000;`, e.g.
```
location / {
    opentelemetry_propagate;
    proxy_pass          http://127.0.0.1:4000;
```
?

**Comment by spencerwilson** [comment]
Thanks for the suggestion. I'll try it out as soon as I can and report back.

**Comment by spencerwilson** [comment]
Yes, moving `opentelemetry_propagate;` from the `http` block to the `location` block resolved it. I'll update this issue's title to reflect the bug.

**Comment by tobiasstadler** [comment]
@spencerwilson #80 should fix your problem. Would you mind testing it please?
