### ISSUE TITLE
otel.so not loaded in http - GLIBC_2.29' not found 

### ISSUE THREAD

**Issue by gioppoluca** [open-telemetry/opentelemetry-cpp-contrib#68]
httpd image from dockerhub (2.4.46)
Using release for ubuntu 20.04
Added it in proper modules place

**Steps to reproduce**
Add module in image and execute
**What is the expected behavior?**
Apache running and using the module

**What is the actual behavior?**

Cannot load /usr/lib/apache2/modules/mod-otel.so into server: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/apache2/modules/mod-otel.so)

**Additional context**

**Comment by TomRoSystems** [comment]
**Dockerfile**

```Dockerfile
FROM httpd
ADD https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/download/httpd%2Fv0.1.0/ubuntu-20.04_mod-otel.so.zip /tmp
ADD https://raw.githubusercontent.com/open-telemetry/opentelemetry-cpp-contrib/main/instrumentation/httpd/opentelemetry.conf /usr/local/apache2/conf/extra/

RUN mv /tmp/ubuntu-20.04_mod-otel.so.zip /usr/local/apache2/modules/mod_otel.so.gz
RUN gzip -d /usr/local/apache2/modules/mod_otel.so.gz

RUN echo "LoadFile /usr/lib/x86_64-linux-gnu/libstdc++.so.6" >> /usr/local/apache2/conf/httpd.conf
RUN echo "LoadModule otel_module modules/mod_otel.so" >> /usr/local/apache2/conf/httpd.conf
RUN echo "Include conf/extra/opentelemetry.conf" >> /usr/local/apache2/conf/httpd.conf
```

Then with default config you'll see spans in `/tmp/output-spans`:
`docker exec -it [CONTAINER_NAME] cat /tmp/output-spans`

Please provide more information about your configuration or ticket will be closed within next 14 days.

**Comment by gioppoluca** [comment]
tried also to build starting from the same image of "http" - is a debian.
Built with no error, copied the file in the httpd image but in this case httpd gose core dump.
Any hints?
Does it work on httpd?

**Comment by gioppoluca** [comment]
my bad!! I forgot to include the conf in the httpd.conf
Thanks for the support
