### ISSUE TITLE
logging trace headers in apache 2.4

### ISSUE THREAD

**Issue by jvilhuber** [open-telemetry/opentelemetry-cpp-contrib#79]
**Describe your environment** Describe any aspect of your environment relevant to the problem, including your platform, build system, version numbers of installed dependencies, etc. If you're reporting a problem with a specific version of a library in this repo, please check whether the problem has been fixed on main branch.
Running with apache httpd 2.4.51 (latest at the time of this writing), using mod_proxy to forward requests. Using the mod-otel 0.1.0 from here https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/download/httpd%2Fv0.1.0/ubuntu-18.04_mod-otel.so.zip

I tried logging the trace header with '%{traceparent}i' but got nothing (a dash/'-' which in apache-speak means "not found"). I assume this is because the header is added by mod-otel AFTER the logging tried to capture it.

**Steps to reproduce**
Using one of the example opentelemetry.conf configs (let's say using 'file' and letting traces go to stderr, i.e. error.log), make a request to my echoserver, which is behind a ProxyPass:

    ProxyPass "/echoserver" "http://echoserver:8080" enablereuse=off

I see the headers coming back from the echo server:

    traceparent=00-e2cb9baa8199a41e746be690a48d6da2-3e2a317ff7539e46-01
    tracestate=

Adding to the LogFormat:

    traceparent=%{traceparent}i

Gets me:

    10.32.3.1 [2021-12-06T11:22:09.329888Z] "GET /echoserver HTTP/1.1" 200 14009 22ms xff=- ua="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0" traceparent=- gw=10.32.3.1 inBytes=2163 OutBytes=14009

I assume this is likely just the way it works and not a bug. If anyone has suggestions how to get the traceID logged, that would be fantastic.

**What is the expected behavior?**
I was hoping to see the traceparent header in the logs.

**What is the actual behavior?**
A dash for the header (which in apache means it was not found).

**Additional context**
Nothing comes to mind.

**Comment by TomRoSystems** [comment]
Well your thinking is correct I was able to log `traceparent` with `traceparent=%{traceparent}i` with mod_otel options:
`OpenTelemetryPropagators trace-context` and `OpenTelemetryIgnoreInbound Off` . Essentially executing test number 7 - https://github.com/open-telemetry/opentelemetry-cpp-contrib/blob/f48500884b1b32efc456790bbcdc2e6cf7a8e630/instrumentation/httpd/tests/07-create-outbound-spans.sh#L14-L15 

from terminal. Are you able to execute this test (please install  [setup-tools.sh](https://github.com/open-telemetry/opentelemetry-cpp-contrib/blob/main/instrumentation/httpd/tests/setup-tools.sh) first )?

> I assume this is because the header is added by mod-otel AFTER the logging tried to capture it.

There must be some other reason as logging is very last in processing pipeline by Apache.

**Comment by jvilhuber** [comment]
I'll try to set up a test environment (or create a Dockerfile that can run the tests?), but if I read test 07 correctly, you're passing IN the traceparent header with curl, right? In my case, we have `OpenTelemetryIgnoreInbound On` (we are the border-gateway in this case) and apache is the originator of the trace. I should have included that in my original report. My apologies.

**Comment by jvilhuber** [comment]
Did a quick test: I enabled `OpenTelemetryIgnoreInbound Off`, and sent in `traceparent: 00-72261f4b29dea7d293e8fbfb6f2c1042-085e794a94f0c55e-01` and I do see that `traceparent` header logged as expected.
The problem is apparently only when `OpenTelemetryIgnoreInbound On` and we're the originator/creator or the trace: Then I get no header in the logs.

**Comment by TomRoSystems** [comment]
I've started working on this one: https://github.com/TomRoSystems/opentelemetry-cpp-contrib/pull/5
Just need to add test.

**Comment by TomRoSystems** [comment]
Fixed in PR https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/97
