### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-cpp-contrib#9]
This repo does not have CODEOWNERS file at the moment. Among other things this means that newly created PRs do not have any default reviewers assigned. Which leads, I believe, to a very long review process.

**Comment by seemk** [comment]
There is now: https://github.com/open-telemetry/opentelemetry-cpp-contrib/blob/main/.github/CODEOWNERS

Can be closed now
